In [4]:
# Faceboook 

import pandas as pd

In [7]:
df = pd.read_csv('dataset_Facebook.csv')

In [8]:
df

,pagetotallikes,type,category,postmonth,postweekday,posthour,paid,lifetimeposttotalreach,lifetimeposttotalimpressions,lifetimeengagedusers,lifetimepostconsumers,lifetimepostconsumptions,lifetimepostimpressionsbypeoplewhohavelikedyourpage,lifetimepostreachbypeoplewholikeyourpage,lifetimepeoplewhohavelikedyourpageandengagedwithyourpost,comment,like,share,totalinteractions
0,139441,2,2,12,4,3,0,2752,5091,178,109,159,3078,1640,119,4,79,17,100
1,139441,3,2,12,3,10,0,10460,19057,1457,1361,1674,11710,6112,1108,5,130,29,164
2,139441,2,3,12,3,3,0,2413,4373,177,113,154,2812,1503,132,0,66,14,80
3,139441,2,2,12,2,10,1,50128,87991,2211,790,1119,61027,32048,1386,58,1572,147,1777
4,139441,2,2,12,2,3,0,7244,13594,671,410,580,6228,3200,396,19,325,49,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,85093,2,3,1,7,10,0,5400,9218,810,756,1003,5654,3230,422,10,125,41,176
368,85093,2,3,1,7,2,0,4684,7536,733,708,985,4750,2876,392,5,53,26,84
369,81370,2,2,1,5,8,0,3480,6229,537,508,687,3961,2104,301,0,53,22,75
370,81370,2,1,1,5,2,0,3778,7216,625,572,795,4742,2388,363,4,93,18,115
371,81370,2,3,1,4,11,0,4156,7564,626,574,832,4534,2452,370,7,91,38,136

In [9]:
df.describe()

,pagetotallikes,type,category,postmonth,postweekday,posthour,paid,lifetimeposttotalreach,lifetimeposttotalimpressions,lifetimeengagedusers,lifetimepostconsumers,lifetimepostconsumptions,lifetimepostimpressionsbypeoplewhohavelikedyourpage,lifetimepostreachbypeoplewholikeyourpage,lifetimepeoplewhohavelikedyourpageandengagedwithyourpost,comment,like,share,totalinteractions
count,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000,3.720000e+02,372.000000,372.000000,372.000000,3.720000e+02,372.000000,372.000000,372.000000,372.000000,372.000000,372.000000
mean,120482.123656,2.040323,1.876344,6.836022,4.212366,7.876344,0.255376,13278.422043,2.983160e+04,887.236559,777.419355,1329.174731,1.711715e+04,6193.787634,574.819892,6.360215,161.395161,25.534946,193.290323
std,17825.647677,0.423040,0.884597,3.756395,2.036211,4.432273,0.436660,21395.541417,8.389262e+04,959.428434,895.748498,1768.215172,6.818961e+04,7314.026346,572.726983,12.713273,232.403038,24.647627,261.455756
min,81370.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.000000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.000000,0.000000,0.000000,0.000000
25%,107907.000000,2.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3329.500000,5.820000e+03,373.000000,306.000000,486.000000,4.113250e+03,2174.000000,276.500000,1.000000,55.000000,11.000000,69.000000
50%,124940.000000,2.000000,2.000000,6.000000,4.000000,9.000000,0.000000,5294.000000,9.146500e+03,625.000000,557.500000,863.500000,6.325500e+03,3493.000000,408.000000,3.000000,97.500000,18.000000,121.500000
75%,137059.000000,2.000000,3.000000,11.000000,6.000000,11.000000,1.000000,11611.000000,2.065800e+04,1062.000000,993.250000,1442.750000,1.356400e+04,7202.000000,622.750000,7.000000,185.250000,32.000000,225.250000
max,139441.000000,4.000000,3.000000,12.000000,7.000000,20.000000,1.000000,158208.000000,1.110282e+06,11452.000000,11328.000000,18115.000000,1.107833e+06,48368.000000,4376.000000,146.000000,1998.000000,181.000000,2177.000000

In [10]:
# First subset: Like and Share
df_subset_1 = df[['like','share']]
df_subset_1

     like  share
0      79     17
1     130     29
2      66     14
3    1572    147
4     325     49
..    ...    ...
367   125     41
368    53     26
369    53     22
370    93     18
371    91     38

[372 rows x 2 columns]

In [12]:
# second subset: Comment and Type
df_subset_2 = df[['comment','type']]
df_subset_2

     comment  type
0          4     2
1          5     3
2          0     2
3         58     2
4         19     2
..       ...   ...
367       10     2
368        5     2
369        0     2
370        4     2
371        7     2

[372 rows x 2 columns]

In [14]:
# merge the data
merged_data  = pd.merge(df_subset_2, df_subset_1, left_on='comment', right_on= 'like')
merged_data

      comment  type  like  share
0           4     2     4      2
1           4     2     4      1
2           4     2     4      0
3           4     2     4      1
4           5     3     5      2
...       ...   ...   ...    ...
1007        7     2     7      0
1008        7     2     7      2
1009        7     2     7      2
1010        7     2     7      3
1011        7     2     7      2

[1012 rows x 4 columns]

In [15]:
# example for merge



# Define a dictionary containing employee data
data1 = {
'key': ['K0', 'K1', 'K2', 'K3'],
'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
'Age':[27, 24, 22, 32],}
# Define a dictionary containing employee data
data2 = {
'key': ['K0', 'K1', 'K2', 'K3'],
'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}
# Convert the dictionary into DataFrame
data1 = pd.DataFrame(data1)
# Convert the dictionary into DataFrame
data2 = pd.DataFrame(data2)

# print(df, "\n\n", df1)
res = pd.merge(data1, data2, on='key')
res

  key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

In [16]:
# Sorting merged_data in descending order wrt 'Like'
merged_data.sort_values(by=['like'],ascending=False)

     comment  type  like  share
910      146     2   146      9
414       60     3    60      7
10        58     2    58     17
11        58     2    58     13
964       56     2    56     17
..       ...   ...   ...    ...
543        0     2     0      0
544        0     2     0      0
545        0     2     0      0
546        0     2     0      0
589        0     2     0      0

[1012 rows x 4 columns]

In [17]:
# Method 1
merged_data.transpose()

,0,1,2,3,4,5,6,7,8,9,...,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011
comment,4,4,4,4,5,0,0,0,0,0,...,0,4,4,4,4,7,7,7,7,7
type,2,2,2,2,3,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
like,4,4,4,4,5,0,0,0,0,0,...,0,4,4,4,4,7,7,7,7,7
share,2,1,0,1,2,0,0,0,0,0,...,0,2,1,0,1,0,2,2,3,2

In [18]:
df

,pagetotallikes,type,category,postmonth,postweekday,posthour,paid,lifetimeposttotalreach,lifetimeposttotalimpressions,lifetimeengagedusers,lifetimepostconsumers,lifetimepostconsumptions,lifetimepostimpressionsbypeoplewhohavelikedyourpage,lifetimepostreachbypeoplewholikeyourpage,lifetimepeoplewhohavelikedyourpageandengagedwithyourpost,comment,like,share,totalinteractions
0,139441,2,2,12,4,3,0,2752,5091,178,109,159,3078,1640,119,4,79,17,100
1,139441,3,2,12,3,10,0,10460,19057,1457,1361,1674,11710,6112,1108,5,130,29,164
2,139441,2,3,12,3,3,0,2413,4373,177,113,154,2812,1503,132,0,66,14,80
3,139441,2,2,12,2,10,1,50128,87991,2211,790,1119,61027,32048,1386,58,1572,147,1777
4,139441,2,2,12,2,3,0,7244,13594,671,410,580,6228,3200,396,19,325,49,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,85093,2,3,1,7,10,0,5400,9218,810,756,1003,5654,3230,422,10,125,41,176
368,85093,2,3,1,7,2,0,4684,7536,733,708,985,4750,2876,392,5,53,26,84
369,81370,2,2,1,5,8,0,3480,6229,537,508,687,3961,2104,301,0,53,22,75
370,81370,2,1,1,5,2,0,3778,7216,625,572,795,4742,2388,363,4,93,18,115
371,81370,2,3,1,4,11,0,4156,7564,626,574,832,4534,2452,370,7,91,38,136

In [20]:
df.type.unique()

array([2, 3, 1, 4])

In [22]:
# Reshape
# Comment is id_vars and Type is value_vars
pd.melt(df, id_vars =['type'], value_vars =['comment'])

     type variable  value
0       2  comment      4
1       3  comment      5
2       2  comment      0
3       2  comment     58
4       2  comment     19
..    ...      ...    ...
367     2  comment     10
368     2  comment      5
369     2  comment      0
370     2  comment      4
371     2  comment      7

[372 rows x 3 columns]

In [24]:
# example
df_temp = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two', 'two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],                    
                   'baz': [1, 2, 3, 4, 5, 6],
                   'zoo': ['x', 'y', 'z', 'q', 'w', 't']})
df_temp

   foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

In [25]:
df_temp.pivot(index='foo', columns='bar', values='baz')

bar  A  B  C
foo
one  1  2  3
two  4  5  6